- name: Update packages on Linux
  ansible.builtin.yum:
    name: '*'
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Update packages on Debian-based Linux
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Windows updates
  ansible.windows.win_updates:
    category_names: ['SecurityUpdates']
  when: ansible_os_family == 'Windows'
