- name: Install and configure database
  ansible.builtin.package:
    name: postgresql
    state: present

- name: Ensure PostgreSQL is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true
