- name: Send incident alert
  ansible.builtin.mail:
    host: smtp.example.com
    port: 587
    username: alert_user
    password: "{{ vault_alert_password }}"
    to: alerts@example.com
    subject: "Critical Incident Detected"
    body: "A critical incident has been detected on {{ inventory_hostname }}."
  when: incident_detected

- name: Send Slack notification on critical event
  community.general.slack:
    token: "{{ vault_slack_token }}"
    msg: "Critical incident on {{ inventory_hostname }}"
    channel: "#alerts"
    username: "monitoring-bot"
  when: incident_detected
