- name: Ensure web server is installed
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ app_list }}"

- name: Configure firewall to allow web traffic
  ansible.builtin.firewalld:
    port: "{{ web_port }}/tcp"
    permanent: true
    state: enabled
  when: ansible_os_family == 'RedHat'

- name: Open firewall for HTTP
  ansible.builtin.ufw:
    rule: allow
    port: "{{ web_port }}"
    proto: tcp
  when: ansible_os_family == 'Debian'
